# https://github.com/ethpandaops/ethereum-package/blob/main/network_params.yaml

network:
  participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.16.7
    cl_type: lighthouse
    # ethpandaops/ethereum-package's recent update requires using the `perfect_peerdas_enabled` option
    # with not less than 16 participants, and disabling `perfect_peerdas_enabled` requires setting the `supernode` flag
    # (https://github.com/ethpandaops/ethereum-package/pull/1217).
    #
    # ssv-mini's main scenario doesn't require so many participants, so we use the `supernode` option. However,
    # ethpandaops/ethereum-package uses the new `--supernode` flag instead of the old `--subscribe-all-data-column-subnets` for lighthouse
    # (https://github.com/ethpandaops/ethereum-package/blob/4026af29de7267898e91e19bb269f26692a84e42/src/cl/lighthouse/lighthouse_launcher.star#L224).
    # `--supernode` is the new flag added in v8.0.0.
    cl_image: sigp/lighthouse:v8.0.1
    validator_count: 32
    count: 2
    supernode: true

  additional_services:
    - dora # Helps to see validators are working

  network_params:
    # this is 'kurtosis' network ID, which is a default network. With this configuration CL /spec endpoint will return CONFIG_NAME=testnet
    network_id: "3151908"
    deneb_fork_epoch: 0
    electra_fork_epoch: 0
    fulu_fork_epoch: 0
    perfect_peerdas_enabled: false

    # 84 = 32 validators * 2(number of el/cl nodes) + 10 (running on SSV/Anchor nodes) + 10 unregistered validators
    # aligns with validator_count configuration under participants section
    preregistered_validator_count: 84
    # NOTE: changes the number of slots in the epoch and potentially some other network settings.
    # docs: https://github.com/ethpandaops/ethereum-package/blob/main/README.md#configuration
    # Supported by Anchor.
    # preset: minimal

  port_publisher:
    cl:
      enabled: true

monitor:
  enabled: false

nodes:
  ssv:
    count: 2
  anchor:
    count: 2

# Docker images configuration
images:
  ssv: "node/ssv"
  anchor: "sigp/anchor:v1.2.0" # if you want to use locally build anchor change to `node/anchor`
  monitor: "ssvlabs/ethereum2-monitor:latest"
  redis: "redis:7.4.2"
  postgres: "postgres:15"
  foundry: "localssv/ssv-network"
  eth_val_tools: "protolambda/eth2-val-tools:latest"
  lighthouse: "sigp/lighthouse:v7.1.0"

extra_params:
  unregistered_validator_count: 10
  # Password to use for all unregistered EIP-2335 keystores (Lighthouse-generated)
  unregistered_validator_password: "aetheria"
