FROM ghcr.io/foundry-rs/foundry:stable

USER root
WORKDIR /app

# Install Git and other dependencies
RUN apt-get update && apt-get install -y git curl bash jq

# Clone the contract source
RUN git clone --branch foundry --depth 1 https://github.com/Zacholme7/ssv-network .

# Install dependencies via Foundry
RUN forge install

# Default command - keep container alive
CMD ["tail", "-f", "/dev/null"]
